/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamblingapp;

/**
 *
 * @author Alex
 */
public class SettingSelectorWindow extends javax.swing.JFrame {
    static GameGUI game;
    static GameController curGame;

    /**
     * Creates new form SettingSelectorWindow
     */
    public SettingSelectorWindow() {
        initComponents();
        nameTextField.setText(GamblingApp.player.name);
        moneyTextField.setText(String.valueOf("$" + GamblingApp.player.balance));
        this.fillSettingFields(GamblingApp.atlanta);
        this.fillSettingFields(GamblingApp.toronto);
        this.fillSettingFields(GamblingApp.amsterdam);
        this.fillSettingFields(GamblingApp.barcelona);
        this.fillSettingFields(GamblingApp.paris);
        this.fillSettingFields(GamblingApp.vegas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        moneyTextField = new javax.swing.JTextField();
        atlantaBtn = new javax.swing.JButton();
        torontoBtn = new javax.swing.JButton();
        amsterdamBtn = new javax.swing.JButton();
        barcelonaBtn = new javax.swing.JButton();
        parisBtn = new javax.swing.JButton();
        vegasBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        feeAtlanta = new javax.swing.JTextField();
        oppAtlanta = new javax.swing.JTextField();
        feeToronto = new javax.swing.JTextField();
        oppToronto = new javax.swing.JTextField();
        feeAmsterdam = new javax.swing.JTextField();
        oppAnsterdam = new javax.swing.JTextField();
        feeBarcelona = new javax.swing.JTextField();
        oppBarcelona = new javax.swing.JTextField();
        feeParis = new javax.swing.JTextField();
        oppParis = new javax.swing.JTextField();
        feeVegas = new javax.swing.JTextField();
        oppVegas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rewardAtlanta = new javax.swing.JTextField();
        rewardToronto = new javax.swing.JTextField();
        rewardAmsterdam = new javax.swing.JTextField();
        rewardBarcelona = new javax.swing.JTextField();
        rewardParis = new javax.swing.JTextField();
        rewardVegas = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        nameTextField.setEditable(false);

        jLabel2.setText("Money:");

        moneyTextField.setEditable(false);

        atlantaBtn.setText("Atlanta");
        atlantaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atlantaBtnActionPerformed(evt);
            }
        });

        torontoBtn.setText("Toronto");
        torontoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torontoBtnActionPerformed(evt);
            }
        });

        amsterdamBtn.setText("Amsterdam");
        amsterdamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amsterdamBtnActionPerformed(evt);
            }
        });

        barcelonaBtn.setText("Barcelona");
        barcelonaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcelonaBtnActionPerformed(evt);
            }
        });

        parisBtn.setText("Paris");
        parisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parisBtnActionPerformed(evt);
            }
        });

        vegasBtn.setText("Vegas");
        vegasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegasBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Entry Fee:");

        jLabel4.setText("Entry Fee:");

        jLabel5.setText("Entry Fee:");

        jLabel6.setText("Entry Fee:");

        jLabel7.setText("Entry Fee:");

        jLabel8.setText("Entry Fee:");

        jLabel9.setText("Opponents:");

        jLabel10.setText("Opponents:");

        jLabel11.setText("Opponents:");

        jLabel12.setText("Opponents:");

        jLabel13.setText("Opponents:");

        jLabel14.setText("Opponents:");

        feeAtlanta.setEditable(false);

        oppAtlanta.setEditable(false);

        feeToronto.setEditable(false);

        oppToronto.setEditable(false);

        feeAmsterdam.setEditable(false);

        oppAnsterdam.setEditable(false);

        feeBarcelona.setEditable(false);

        oppBarcelona.setEditable(false);

        feeParis.setEditable(false);

        oppParis.setEditable(false);

        feeVegas.setEditable(false);

        oppVegas.setEditable(false);

        jLabel15.setText("Reward:");

        jLabel16.setText("Reward:");

        jLabel17.setText("Reward:");

        jLabel18.setText("Reward:");

        jLabel19.setText("Reward:");

        jLabel20.setText("Reward:");

        rewardAtlanta.setEditable(false);

        rewardToronto.setEditable(false);

        rewardAmsterdam.setEditable(false);

        rewardBarcelona.setEditable(false);

        rewardParis.setEditable(false);

        rewardVegas.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moneyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atlantaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(rewardAtlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oppAtlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(feeAtlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(torontoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(feeToronto)
                                    .addComponent(oppToronto)
                                    .addComponent(rewardToronto, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amsterdamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addComponent(rewardAmsterdam))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(feeAmsterdam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(oppAnsterdam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barcelonaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(10, 10, 10)
                                .addComponent(feeBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(18, 18, 18)
                                    .addComponent(rewardBarcelona))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(oppBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(8, 8, 8)
                                .addComponent(feeParis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(18, 18, 18)
                                    .addComponent(rewardParis))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(oppParis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oppVegas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(vegasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rewardVegas))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(feeVegas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(moneyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atlantaBtn)
                    .addComponent(torontoBtn)
                    .addComponent(amsterdamBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(feeAtlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feeToronto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feeAmsterdam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rewardAtlanta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(rewardToronto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rewardAmsterdam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oppAtlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(oppToronto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(oppAnsterdam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcelonaBtn)
                    .addComponent(parisBtn)
                    .addComponent(vegasBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(feeBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feeParis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feeVegas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(rewardBarcelona)
                    .addComponent(rewardParis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rewardVegas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(oppBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(oppParis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(oppVegas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atlantaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atlantaBtnActionPerformed
        // TODO add your handling code here:
        GameGUI.setSetting(GamblingApp.atlanta);
        this.setupGame(GamblingApp.atlanta);
        GameController.firstGame = false;
    }//GEN-LAST:event_atlantaBtnActionPerformed

    private void torontoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torontoBtnActionPerformed
        // TODO add your handling code here:
        GameGUI.setSetting(GamblingApp.toronto);
        this.setupGame(GamblingApp.toronto);
    }//GEN-LAST:event_torontoBtnActionPerformed

    private void amsterdamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amsterdamBtnActionPerformed
        // TODO add your handling code here:
        GameGUI.setSetting(GamblingApp.toronto);
        this.setupGame(GamblingApp.amsterdam);
    }//GEN-LAST:event_amsterdamBtnActionPerformed

    private void barcelonaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcelonaBtnActionPerformed
        // TODO add your handling code here:
        GameGUI.setSetting(GamblingApp.barcelona);
        this.setupGame(GamblingApp.barcelona);
    }//GEN-LAST:event_barcelonaBtnActionPerformed

    private void parisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parisBtnActionPerformed
        // TODO add your handling code here:
        GameGUI.setSetting(GamblingApp.paris);
        this.setupGame(GamblingApp.paris);
    }//GEN-LAST:event_parisBtnActionPerformed

    private void vegasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegasBtnActionPerformed
        // TODO add your handling code here:
        GameGUI.setSetting(GamblingApp.vegas);
        this.setupGame(GamblingApp.vegas);
    }//GEN-LAST:event_vegasBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingSelectorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingSelectorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingSelectorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingSelectorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingSelectorWindow().setVisible(true);
            }
        });
    }
    
    private void fillSettingFields(Setting s){
        if(s.name.equals("Atlanta")){
            feeAtlanta.setText(String.valueOf("$" + GamblingApp.atlanta.entryFee));
            oppAtlanta.setText(String.valueOf(GamblingApp.atlanta.opponentQty));
            rewardAtlanta.setText(String.valueOf("$" + GamblingApp.atlanta.reward));
        }
        else if(s.name.equals("Toronto")){
            feeToronto.setText(String.valueOf("$" + GamblingApp.toronto.entryFee));
            oppToronto.setText(String.valueOf(GamblingApp.toronto.opponentQty));
            rewardToronto.setText(String.valueOf("$" + GamblingApp.toronto.reward));
        }
        else if(s.name.equals("Amsterdam")){
            feeAmsterdam.setText(String.valueOf("$" + GamblingApp.amsterdam.entryFee));
            oppAnsterdam.setText(String.valueOf(GamblingApp.amsterdam.opponentQty));
            rewardAmsterdam.setText(String.valueOf("$" + GamblingApp.amsterdam.reward));
        }
        else if(s.name.equals("Barcelona")){
            feeBarcelona.setText(String.valueOf("$" + GamblingApp.barcelona.entryFee));
            oppBarcelona.setText(String.valueOf(GamblingApp.barcelona.opponentQty));
            rewardBarcelona.setText(String.valueOf("$" + GamblingApp.barcelona.reward));
        }
        else if(s.name.equals("Paris")){
            feeParis.setText(String.valueOf("$" + GamblingApp.paris.entryFee));
            oppParis.setText(String.valueOf(GamblingApp.paris.opponentQty));
            rewardParis.setText(String.valueOf("$" + GamblingApp.paris.reward));
        }
        else{
            feeVegas.setText(String.valueOf("$" + GamblingApp.vegas.entryFee));
            oppVegas.setText(String.valueOf(GamblingApp.vegas.opponentQty));
            rewardVegas.setText(String.valueOf("$" + GamblingApp.vegas.reward));
        }
    }
    
    private void setupGame(Setting s){
        if(GamblingApp.player.enterSetting(s)){
            moneyTextField.setText("$" + String.valueOf(GamblingApp.player.balance));
            curGame = new GameController(s);
            game = new GameGUI();
            game.setVisible(true);
        }
    }
    
    public void updatePlayerBalance(){
        moneyTextField.setText(String.valueOf("$" + GamblingApp.player.balance));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amsterdamBtn;
    private javax.swing.JButton atlantaBtn;
    private javax.swing.JButton barcelonaBtn;
    private javax.swing.JTextField feeAmsterdam;
    private javax.swing.JTextField feeAtlanta;
    private javax.swing.JTextField feeBarcelona;
    private javax.swing.JTextField feeParis;
    private javax.swing.JTextField feeToronto;
    private javax.swing.JTextField feeVegas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField moneyTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField oppAnsterdam;
    private javax.swing.JTextField oppAtlanta;
    private javax.swing.JTextField oppBarcelona;
    private javax.swing.JTextField oppParis;
    private javax.swing.JTextField oppToronto;
    private javax.swing.JTextField oppVegas;
    private javax.swing.JButton parisBtn;
    private javax.swing.JTextField rewardAmsterdam;
    private javax.swing.JTextField rewardAtlanta;
    private javax.swing.JTextField rewardBarcelona;
    private javax.swing.JTextField rewardParis;
    private javax.swing.JTextField rewardToronto;
    private javax.swing.JTextField rewardVegas;
    private javax.swing.JButton torontoBtn;
    private javax.swing.JButton vegasBtn;
    // End of variables declaration//GEN-END:variables
}
